[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/src/=lib/chainlink-brownie-contracts/contracts/src/",
    "@solmate/=lib/solmate/src/"
]
fs_permissions = [
    {access = "read", path = "./broadcast"},
    {access = "read", path = "./reports"},
]

[fuzz]
runs = 100 # Number of fuzz runs
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
